### ISSUE TITLE
New npm package to publish

### ISSUE THREAD

**Issue by tfalvo** [Matschik/freebox-sdk-js#1]
Hi. Thanks for your work.
I wasn't able to make an https connection with current version 0.6 of npm package.
However, it works like a charm with your current master branch.

Would you have the opportunity to publish the 0.7 version of npm package ?
Thanks a lot !

**Comment by Matschik** [comment]
Hello !
I just published and tested the lastest version (0.7.4) to npm. 

Thank you very much for this information !
Enjoy !

**Comment by tfalvo** [comment]
👍 Great. Thanks.
